spring:
    datasource:
        url: jdbc:mysql://localhost:3306/student_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver


    data:
        redis:
            host: localhost
            port: 6379
            database: 0
            # 如果有密码
            # password: 123456


mybatis:
    mapper-locations: com.rainbow.demo.mapper/*.xml
    type-aliases-package: com.rainbow.demo.entity

spring.application.name: demo

# # 服务器端口
server.port: 8080